version: '3'
services:
  php:
    container_name: 'myphp'
    build: ./php
    ports:
      - 9000:9000
    restart: always
    volumes:
      - ./wwwroot:/mnt/wwwroot
    networks:
      app_net:
        ipv4_address: 10.1.0.100
    environment:
      - TZ=Asia/Shanghai
  mysql:
    container_name: 'mysql'
    image: 'mysql:5.7'
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/log:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD='test'
      - TZ=Asia/Shanghai
    networks:
      app_net:
        ipv4_address: 10.1.0.101
    command:
      --max_connections=2048
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:6.2.6
    container_name: 'redis'
    restart: always
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
      - ./redis/data:/data
      - ./redis/logs:/logs
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      app_net:
        ipv4_address: 10.1.0.102
    environment:
      - TZ=Asia/Shanghai
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      config:
        - subnet: 10.1.0.0/16
